# Adaptive PDE discretizations on cartesian grids 
## Volume : GPU accelerated methods
## Part : Reproducibility
## Chapter : Riemannian metrics

In this notebook, we solve isotropic eikonal equations on the CPU and the GPU, and check that they produce consistent results.

In [1]:
import sys; sys.path.insert(0,"../..")
#from Miscellaneous import TocTools; print(TocTools.displayTOC('Isotropic_Repro','GPU'))

In [2]:
import cupy as cp
import numpy as np
import itertools
from matplotlib import pyplot as plt
np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float=lambda x: "%5.3g" % x))

In [3]:
from agd import HFMUtils
from agd import AutomaticDifferentiation as ad
from agd import Metrics
from agd import FiniteDifferences as fd
from agd import LinearParallel as lp
import agd.AutomaticDifferentiation.cupy_generic as cugen

norm_infinity = ad.Optimization.norm_infinity
from agd.HFMUtils import RunGPU,RunSmart

In [4]:
def ReloadPackages():
    from Miscellaneous.rreload import rreload
    global HFMUtils,ad,cugen,RunGPU,RunSmart,Metrics
    HFMUtils,ad,cugen,RunGPU,Metrics = rreload([HFMUtils,ad,cugen,RunGPU,Metrics],"../..")    
    RunSmart = cugen.cupy_get_args(HFMUtils.RunSmart,dtype64=True,iterables=(dict,Metrics.Base))

In [5]:
cp = ad.functional.decorate_module_functions(cp,cugen.set_output_dtype32) # Use float32 and int32 types in place of float64 and int64
plt = ad.functional.decorate_module_functions(plt,cugen.cupy_get_args)
RunSmart = cugen.cupy_get_args(RunSmart,dtype64=True,iterables=(dict,Metrics.Base))

### 0.1 Utilities

In [24]:
#from Notebooks_GPU.ExportedCode.Isotropic_Repro import RunCompare
def RunCompare(gpuIn,check=True):
    gpuOut = RunGPU(gpuIn)
    if gpuIn.get('verbosity',1): print("---")
    cpuIn = gpuIn.copy(); cpuIn.pop('traits',None)
    cpuOut = RunSmart(cpuIn)
    print("Max |gpuValues-cpuValues| : ", norm_infinity(gpuOut['values'].get()-cpuOut['values']))
    cpuTime = cpuOut['FMCPUTime']; gpuTime = gpuOut['solverGPUTime'];
    print(f"Solver time (s). GPU : {gpuTime}, CPU : {cpuTime}. Device acceleration : {cpuTime/gpuTime}")
    assert not check or cp.allclose(gpuOut['values'],cpuOut['values'],atol=1e-6)
    return gpuOut,cpuOut

In [25]:
factor_variants = [
    {}, # Default
    {"seedRadius":2}, # Spread seed information
    {"factorizationRadius":10,'factorizationPointChoice':'Key'} # Source factorization
]
multip_variants = [
    {'multiprecision':False}, # Default
    {'multiprecision':True}, # Reduces roundoff errors
]
order_variants = [
    {'order':1}, # Default
    {'order':2}, # More accurate on smooth instances
]

## 1. Two dimensions

### 1.1 Isotropic metric

In [9]:
n=4000
hfmIn = HFMUtils.dictIn({
    'model':'Riemann2',
    'metric':Metrics.Riemann(cp.eye(2)),
    'seeds':cp.array([[0.5,0.5]]),
    'exportValues':1,
    'traits':{
        'niter_i':24,'shape_i':(12,12), # Best
    }
})
hfmIn.SetRect([[0,1],[0,1]],dimx=n+1,sampleBoundary=True)

Casting output of function eye from float64 to float32
Casting output of function array from float64 to float32


In [9]:
_,cpuOut = RunCompare(hfmIn,check=False)

Setting the kernel traits.
Prepating the domain data (shape,metric,...)
Preparing the values array (setting seeds,...)
Preparing the GPU kernel
Setup and run the eikonal solver
GPU solve took 0.4770023822784424 seconds, in 668 iterations.
Post-Processing
---
Field verbosity defaults to 1
Field order defaults to 1
Field seedRadius defaults to 0
Fast marching solver completed in 17.016 s.
Max |gpuValues-cpuValues| :  0.49105587362191727
Solver time (s). GPU : 0.4770023822784424, CPU : 17.016. Device acceleration : 35.672777814487276


In [10]:
n=200; hfmInS = hfmIn.copy() # Define a small instance for bit-consistency validation
hfmInS.SetRect([[0,1],[0,1]],dimx=n+1,sampleBoundary=True)
X = hfmInS.Grid()
cost = np.prod(np.sin(2*np.pi*X))+1.1
hfmInS.update({
    'metric': Metrics.Riemann(cost**2*fd.as_field(cp.eye(2),X.shape[1:])), # Isotropic but non-constant metric
    'verbosity':0,
})

Casting output of function eye from float64 to float32


In [11]:
RunCompare(hfmInS);

Max |gpuValues-cpuValues| :  4.017569794623199e-07
Solver time (s). GPU : 0.03299975395202637, CPU : 0.027. Device acceleration : 0.8181879185902854


In [12]:
for fact,multip in itertools.product(factor_variants,multip_variants):
    print(f"\nReproducibility with options : {fact}, {multip}")
    RunCompare({**hfmInS,**fact,**multip})


Reproducibility with options : {}, {'multiprecision': False}
Max |gpuValues-cpuValues| :  4.017569794623199e-07
Solver time (s). GPU : 0.008000373840332031, CPU : 0.027. Device acceleration : 3.3748422934795563

Reproducibility with options : {}, {'multiprecision': True}
Max |gpuValues-cpuValues| :  6.320754353250635e-08
Solver time (s). GPU : 0.010999679565429688, CPU : 0.027. Device acceleration : 2.4546169585573088

Reproducibility with options : {'seedRadius': 2}, {'multiprecision': False}
Max |gpuValues-cpuValues| :  4.202669309227858e-07
Solver time (s). GPU : 0.010000944137573242, CPU : 0.025. Device acceleration : 2.4997639878894797

Reproducibility with options : {'seedRadius': 2}, {'multiprecision': True}
Max |gpuValues-cpuValues| :  1.0889257084922832e-07
Solver time (s). GPU : 0.010991096496582031, CPU : 0.026. Device acceleration : 2.3655510629067242

Reproducibility with options : {'factorizationRadius': 10, 'factorizationPointChoice': 'Key'}, {'multiprecision': False}
M

In [13]:
hfmInS.update({
    'seeds':[[0.0,1.]],
    'order':2,
})

In [15]:
for fact,multip in itertools.product((factor_variants[0],factor_variants[2]),multip_variants):
    print(f"\nReproducibility with options : {fact}, {multip}")
    RunCompare({**hfmInS,**fact,**multip})


Reproducibility with options : {}, {'multiprecision': False}
Max |gpuValues-cpuValues| :  4.88107854068609e-06
Solver time (s). GPU : 0.021503448486328125, CPU : 0.04. Device acceleration : 1.8601667553663297

Reproducibility with options : {}, {'multiprecision': True}
Max |gpuValues-cpuValues| :  1.291459792440719e-07
Solver time (s). GPU : 0.02249884605407715, CPU : 0.038. Device acceleration : 1.688975510506851

Reproducibility with options : {'factorizationRadius': 10, 'factorizationPointChoice': 'Key'}, {'multiprecision': False}
Max |gpuValues-cpuValues| :  4.88107854068609e-06
Solver time (s). GPU : 0.02249908447265625, CPU : 0.041. Device acceleration : 1.8222963716514073

Reproducibility with options : {'factorizationRadius': 10, 'factorizationPointChoice': 'Key'}, {'multiprecision': True}
Max |gpuValues-cpuValues| :  1.291459792440719e-07
Solver time (s). GPU : 0.022498607635498047, CPU : 0.04. Device acceleration : 1.7778877985715194


### 1.2 Smooth anisotropic metric

In [39]:
n=20
hfmIn = HFMUtils.dictIn({
    'model':'Riemann2',
    'seeds':cp.array([[0.,0.]]),
    'exportValues':1,
    'traits':{
        'niter_i':24,'shape_i':(12,12), # Best
    },
    'metric':cp.array([1.,0.2,1.])
})
hfmIn.SetRect([[-np.pi,np.pi],[-np.pi,np.pi]],dimx=n+1,sampleBoundary=True)
X=hfmIn.Grid()

Casting output of function array from float64 to float32
Casting output of function array from float64 to float32


In [40]:
def height(x):
     return np.sin(x[0])*np.sin(x[1])

In [41]:
X_ad = ad.Dense.identity(constant=X,shape_free=(2,))
tensors = lp.outer_self( height(X_ad).gradient() ) + fd.as_field(cp.eye(2),X.shape[1:])
#hfmIn['metric'] = Metrics.Riemann(tensors)

Casting output of function eye from float64 to float32


In [42]:
gpuOut,cpuOut = RunCompare(hfmIn,check=False)

Setting the kernel traits.
Prepating the domain data (shape,metric,...)
Preparing the values array (setting seeds,...)
Preparing the GPU kernel
Setup and run the eikonal solver
GPU solve took 0.0034995079040527344 seconds, in 4 iterations.
Post-Processing
---
Field verbosity defaults to 1
Field order defaults to 1
Field seedRadius defaults to 0
Fast marching solver completed in 0.001 s.
Max |gpuValues-cpuValues| :  1.6877359661175122
Solver time (s). GPU : 0.0034995079040527344, CPU : 0.001. Device acceleration : 0.28575446246082575


In [43]:
gpuOut['values'].get()-cpuOut['values']

array([[0.813, 0.776, 0.742, 0.711, 0.686, 0.666, 0.652, 0.645, 0.645, 0.655, 0.675, 0.806, 0.928,  1.04,  1.14,  1.24,  1.34,  1.43,  1.52,   1.6,  1.69],
       [0.776, 0.735, 0.697, 0.663, 0.634,  0.61, 0.591,  0.58, 0.576, 0.582, 0.598, 0.733, 0.855, 0.964,  1.07,  1.16,  1.26,  1.35,  1.44,  1.52,   1.6],
       [0.742, 0.697, 0.656, 0.618, 0.585, 0.556, 0.533, 0.517, 0.509,  0.51, 0.522, 0.662, 0.782,  0.89, 0.992,  1.09,  1.18,  1.27,  1.35,  1.44,  1.52],
       [0.711, 0.663, 0.618, 0.577, 0.539, 0.506, 0.478, 0.457, 0.444,  0.44, 0.447, 0.591,  0.71, 0.817, 0.916,  1.01,   1.1,  1.18,  1.27,  1.35,  1.43],
       [0.686, 0.634, 0.585, 0.539, 0.497,  0.46, 0.427, 0.401, 0.382, 0.372, 0.374,  0.52, 0.638, 0.743,  0.84, 0.931,  1.02,   1.1,  1.18,  1.26,  1.34],
       [0.666,  0.61, 0.556, 0.506,  0.46, 0.418,  0.38, 0.348, 0.323, 0.308, 0.303,  0.45, 0.566, 0.668, 0.761, 0.848, 0.931,  1.01,  1.09,  1.16,  1.24],
       [0.652, 0.591, 0.533, 0.478, 0.427,  0.38, 0.337,   0.3, 

In [45]:
cpuOut['values']

array([[ 5.13,  4.89,  4.65,  4.43,  4.22,  4.02,  3.83,  3.66,  3.52,  3.39,   3.3,  3.24,  3.23,  3.27,  3.34,  3.44,  3.57,  3.71,  3.88,  4.06,  4.26],
       [ 4.89,  4.64,  4.39,  4.16,  3.94,  3.73,  3.53,  3.36,   3.2,  3.08,  2.98,  2.92,  2.93,  2.97,  3.06,  3.17,  3.31,  3.48,  3.66,  3.85,  4.06],
       [ 4.65,  4.39,  4.14,   3.9,  3.67,  3.45,  3.24,  3.06,  2.89,  2.76,  2.66,  2.61,  2.62,  2.68,  2.78,  2.91,  3.07,  3.25,  3.44,  3.66,  3.88],
       [ 4.43,  4.16,   3.9,  3.64,   3.4,  3.17,  2.95,  2.76,  2.58,  2.44,  2.33,  2.29,  2.32,   2.4,  2.52,  2.67,  2.84,  3.04,  3.25,  3.48,  3.71],
       [ 4.22,  3.94,  3.67,   3.4,  3.15,   2.9,  2.67,  2.46,  2.28,  2.12,  2.01,  1.98,  2.02,  2.12,  2.26,  2.43,  2.63,  2.84,  3.07,  3.31,  3.57],
       [ 4.02,  3.73,  3.45,  3.17,   2.9,  2.64,   2.4,  2.18,  1.98,  1.81,  1.68,  1.66,  1.73,  1.86,  2.02,  2.21,  2.43,  2.67,  2.91,  3.17,  3.44],
       [ 3.83,  3.53,  3.24,  2.95,  2.67,   2.4,  2.14,   1.9, 

In [31]:
type(np.zeros_like(cp.ones(2)))

Casting output of function ones from float64 to float32


cupy.core.core.ndarray

In [37]:
ad.Dense.identity((2,2)).__module__

'agd.AutomaticDifferentiation.Dense'

In [32]:
np.zeros(0)

array([], dtype=float64)

In [33]:
np.array((cp.array(1),cp.array(1)))

array([array(1), array(1)], dtype=object)

In [35]:
type(ad.Dense.identity((2,2)))

agd.AutomaticDifferentiation.Dense.denseAD

In [26]:
ad.Dense.identity(constant=cp.zeros(2))

Casting output of function zeros from float64 to float32


ValueError: object __array__ method not producing an array

In [25]:
ad.Dense.identity(constant=,shape_free=(2,))

ValueError: object __array__ method not producing an array

In [24]:
height(X)

array([[2.28e-14, 4.67e-08, 8.88e-08, 1.22e-07, 1.44e-07, 1.51e-07, 1.44e-07, 1.22e-07, 8.88e-08, 4.67e-08, -2.51e-23, -4.67e-08, -8.88e-08, -1.22e-07, -1.44e-07, -1.51e-07, -1.44e-07, -1.22e-07, -8.88e-08, -4.67e-08, -2.28e-14],
       [4.67e-08, 0.0955, 0.182,  0.25, 0.294, 0.309, 0.294,  0.25, 0.182, 0.0955, -5.15e-17, -0.0955, -0.182, -0.25, -0.294, -0.309, -0.294, -0.25, -0.182, -0.0955, -4.67e-08],
       [8.88e-08, 0.182, 0.345, 0.476, 0.559, 0.588, 0.559, 0.476, 0.345, 0.182, -9.79e-17, -0.182, -0.345, -0.476, -0.559, -0.588, -0.559, -0.476, -0.345, -0.182, -8.88e-08],
       [1.22e-07,  0.25, 0.476, 0.655, 0.769, 0.809, 0.769, 0.655, 0.476,  0.25, -1.35e-16, -0.25, -0.476, -0.655, -0.769, -0.809, -0.769, -0.655, -0.476, -0.25, -1.22e-07],
       [1.44e-07, 0.294, 0.559, 0.769, 0.905, 0.951, 0.905, 0.769, 0.559, 0.294, -1.58e-16, -0.294, -0.559, -0.769, -0.905, -0.951, -0.905, -0.769, -0.559, -0.294, -1.44e-07],
       [1.51e-07, 0.309, 0.588, 0.809, 0.951,     1, 0.951, 0.809,

In [ ]:
ad.Dense.identity(constant = 