# Investigating numpy-cupy compatibility

In [6]:
import cupyx.scipy.sparse.linalg.lsqr as solver
#cupy.cupyx

ModuleNotFoundError: No module named 'cupyx.scipy.sparse.linalg.lsqr'

In [5]:
cupyx.scipy.sparse.linalg.lsqr

<function cupyx.scipy.sparse.linalg.solve.lsqr(A, b)>

In [1]:
import cupy as cp
import numpy as np
import sys; sys.path.insert(0,"../..")

In [16]:
np.zeros(shape=(0,))

array([], dtype=float64)

In [18]:
cp.arange(10,dtype=np.int32).dtype

dtype('int32')

In [14]:
spmod = cp.cupyx.scipy.sparse

data=cp.array([1.,2.],dtype=np.float32)
row = cp.array([0,1],dtype=np.int32)
col = cp.array([0,1],dtype=np.int32)
spmat = spmod.coo_matrix((data,(row,col)))
print(spmat.dtype)
print(spmat.todense())
print(spmat.tocsr())

spmod.linalg.lsqr(spmat,cp.array([2.,3.],dtype=np.float32))

float32
[[1. 0.]
 [0. 2.]]
  (0, 0)	1.0
  (1, 1)	2.0


(array([2. , 1.5]), None, None, None, None, None, None, None, None, None)

In [2]:
from agd import Metrics 
from agd import LinearParallel as lp

In [3]:
metric = Metrics.Riemann(cp.eye(2,dtype=np.float32))
metric2 = metric.rescale((0.5,2.))

In [4]:
metric2.m

array([[4.  , 0.  ],
       [0.  , 0.25]], dtype=float32)

In [5]:
lp.trace(metric2.m)

array(4.25, dtype=float32)

In [10]:
sum(metric2.m[i,i] for i in range(2))

array(4.25, dtype=float32)

In [6]:
metric2.cost_bound()

array(2.0615528, dtype=float32)

In [3]:
(cp.array(1.,dtype=np.float64)*cp.array(2.,dtype=np.float32)).dtype

dtype('float64')

In [8]:
np.mean(cp.eye(2))

array(0.5)

In [7]:
np.broadcast_to(cp.array(1.),3)

TypeError: object of type 'int' has no len()

In [2]:
from agd import AutomaticDifferentiation as ad

In [5]:
type(ad.array([[1,2],[3,4]]))

numpy.ndarray

In [3]:
zz = cp.zeros((2,2))

In [4]:
np.array(zz)

ValueError: object __array__ method not producing an array

## Familiar funcs

In [6]:
zz2 = np.reshape(zz,(4,))
type(zz2)

In [10]:
zz2 = np.stack((zz,zz),axis=0)
type(zz2)

cupy.core.core.ndarray

In [19]:
zz2 = np.broadcast_to(zz,(2,2,2))
type(zz2)

cupy.core.core.ndarray

## No left operand bug 

In [16]:
z = cp.array(0.)
type(np.float(1.)+z)

cupy.core.core.ndarray