In [1]:
import sys; sys.path.insert(0,"../..") # Allow import of agd from parent directory (useless if conda package installed)
#from Miscellaneous import TocTools; print(TocTools.displayTOC('SensitivitySL','FMM'))

In [2]:
from agd import AutomaticDifferentiation as ad
from agd.HFMUtils.HFM_CUDA import nonzero_untidy

In [3]:
import numpy as np
import types
import os

In [11]:
arr = np.zeros((400,100))
nonzero_untidy.nonzero(arr,log2_size_i=5)

shape_i : [8 4]


RuntimeError: No active exception to reraise

In [14]:
def f(x): return x+1
kwargs = {}
f(1,**kwargs)

2

In [55]:
np.uint8

numpy.uint8

In [54]:
os.path.getmtime("dirtest/TODO_.txt")

1584974616.876393

In [40]:
np.meshgrid(np.arange(5,dtype=np.float32))

[array([0., 1., 2., 3., 4.], dtype=float32)]

In [33]:
shape=(2,2)
np.mgrid.__getitem__((slice(2),slice(2)))

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

In [38]:
np.mgrid.__getitem__(tuple(slice(s) for s in shape))

array([[[0, 0],
        [1, 1]],

       [[0, 1],
        [0, 1]]])

In [ ]:
np.meshgrid(

In [36]:
grid = np.mgrid[:100,:100]
grid.nbytes
grid[:,2,1]

array([2, 1])

In [22]:
np.linspace((10,10))

TypeError: _linspace_dispatcher() missing 1 required positional argument: 'stop'

In [4]:
print(np)

<module 'numpy' from '/Users/mirebeau/opt/miniconda3/envs/agd-hfm_dev/lib/python3.8/site-packages/numpy/__init__.py'>


In [12]:
np2,dec = ad.cupy_generic.decorate_module_functions(np,ad.cupy_generic.set_output_dtype32,ret_decorated=True)

In [9]:
dec

['show_config',
 'nested_iters',
 'arange',
 'array',
 'zeros',
 'count_nonzero',
 'empty',
 'fromstring',
 'fromfile',
 'frombuffer',
 'int_asbuffer',
 'where',
 'argwhere',
 'copyto',
 'concatenate',
 'fastCopyAndTranspose',
 'lexsort',
 'set_numeric_ops',
 'can_cast',
 'promote_types',
 'min_scalar_type',
 'result_type',
 'isfortran',
 'empty_like',
 'zeros_like',
 'ones_like',
 'correlate',
 'convolve',
 'inner',
 'dot',
 'outer',
 'vdot',
 'roll',
 'rollaxis',
 'moveaxis',
 'cross',
 'tensordot',
 'fromiter',
 'array_equal',
 'array_equiv',
 'indices',
 'fromfunction',
 'isclose',
 'load',
 'loads',
 'isscalar',
 'binary_repr',
 'base_repr',
 'ones',
 'identity',
 'allclose',
 'compare_chararrays',
 'putmask',
 'flatnonzero',
 'full',
 'full_like',
 'shares_memory',
 'may_share_memory',
 'alen',
 'all',
 'alltrue',
 'amax',
 'amin',
 'any',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'around',
 'choose',
 'clip',
 'compress',
 'cumprod',
 'cumproduct',
 'cumsum',
 'diagona

In [13]:
np2.arange(10.)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [19]:
np2.arange(11.)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
      dtype=float32)

In [5]:
isinstance(np.__dict__['arange'],types.FunctionType)

False

In [6]:
isinstance(np.meshgrid,types.FunctionType)

True

In [7]:
str(type(np.arange))

"<class 'builtin_function_or_method'>"

In [8]:
isinstance(np.arange,types.BuiltinMethodType)

True

In [9]:
dir(types)

['AsyncGeneratorType',
 'BuiltinFunctionType',
 'BuiltinMethodType',
 'CellType',
 'ClassMethodDescriptorType',
 'CodeType',
 'CoroutineType',
 'DynamicClassAttribute',
 'FrameType',
 'FunctionType',
 'GeneratorType',
 'GetSetDescriptorType',
 'LambdaType',
 'MappingProxyType',
 'MemberDescriptorType',
 'MethodDescriptorType',
 'MethodType',
 'MethodWrapperType',
 'ModuleType',
 'SimpleNamespace',
 'TracebackType',
 'WrapperDescriptorType',
 '_GeneratorWrapper',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_calculate_meta',
 '_cell_factory',
 'coroutine',
 'new_class',
 'prepare_class',
 'resolve_bases']

In [10]:
builtin_function_or_method

NameError: name 'builtin_function_or_method' is not defined

In [11]:
type(np.linspace)

function

In [12]:
type(np.ndarray)

type

In [13]:
callable(np.ndarray)

True

In [14]:
np2 = ad.cupy_generic.decorate_module_functions(np,ad.cupy_generic.set_output_dtype32)

decorating show_config
decorating nested_iters
decorating arange
decorating array
decorating zeros
decorating count_nonzero
decorating empty
decorating fromstring
decorating fromfile
decorating frombuffer
decorating int_asbuffer
decorating where
decorating argwhere
decorating copyto
decorating concatenate
decorating fastCopyAndTranspose
decorating lexsort
decorating set_numeric_ops
decorating can_cast
decorating promote_types
decorating min_scalar_type
decorating result_type
decorating isfortran
decorating empty_like
decorating zeros_like
decorating ones_like
decorating correlate
decorating convolve
decorating inner
decorating dot
decorating outer
decorating vdot
decorating roll
decorating rollaxis
decorating moveaxis
decorating cross
decorating tensordot
decorating fromiter
decorating array_equal
decorating array_equiv
decorating indices
decorating fromfunction
decorating isclose
decorating load
decorating loads
decorating isscalar
decorating binary_repr
decorating base_repr
decoratin

In [12]:
#import types
#isinstance(np.,types.FunctionType)

In [15]:
type(np.arange)

function

In [18]:
np.arange(10)

Casting output of function arange from int64 to int32


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [7]:
@ad.cupy_generic.set_output_dtype32(silent=True)
def f(arr): 
    """function f"""
    return arr+1

@ad.cupy_generic.set_output_dtype32
def g(arr):
    """function g"""
    return arr*2

In [8]:
fdec = ad.cupy_generic.set_output_dtype32(f)

In [9]:
help(fdec)

Help on function f in module __main__:

f(arr)
    function f



In [10]:
x = np.arange(10.)

In [11]:
g(x).dtype

Casting output of function g from float64 to float32


dtype('float32')

In [12]:
fdec(x).dtype

dtype('float32')

In [13]:
type(x[0])

numpy.float64

In [14]:
np.int64

numpy.int64

In [15]:
np.dtype('int64').type

numpy.int64

In [16]:
np.dtype(np.int64)

dtype('int64')

In [17]:
np.int64==np.float64

False