In [7]:
def code_line(s):
    s=s.replace("[[","ORDER_SWAP(")
    s=s.replace("],[",");ORDER_SWAP(")
    s=s.replace("]]",");")
    return s

def code_network(s):
    s = s.split("\n")
    n = int(s[0])
    s = (f"template<typename T> void sort{n}(const T values[{n}],int order[{n}])" "{\n"+
         "\n".join(code_line(l) for l in s[1:])+
         "};\n")
    return s
def code_networks(s):
    s = s.split('--- ')[1:]
    return "\n".join(code_network(l) for l in s)

In [8]:
s="""
--- 2
[[0,1]]
--- 3
[[1,2]]
[[0,2]]
[[0,1]]
--- 4
[[0,1],[2,3]]
[[0,2],[1,3]]
[[1,2]]
--- 5
[[0,1],[3,4]]
[[2,4]]
[[2,3],[1,4]]
[[0,3]]
[[0,2],[1,3]]
[[1,2]]
--- 6
[[1,2],[4,5]]
[[0,2],[3,5]]
[[0,1],[3,4],[2,5]]
[[0,3],[1,4]]
[[2,4],[1,3]]
[[2,3]]
--- 7
[[1,2],[3,4],[5,6]]
[[0,2],[3,5],[4,6]]
[[0,1],[4,5],[2,6]]
[[0,4],[1,5]]
[[0,3],[2,5]]
[[1,3],[2,4]]
[[2,3]]
--- 8
[[0,1],[2,3],[4,5],[6,7]]
[[0,2],[1,3],[4,6],[5,7]]
[[1,2],[5,6],[0,4],[3,7]]
[[1,5],[2,6]]
[[1,4],[3,6]]
[[2,4],[3,5]]
[[3,4]]
--- 9
[[0,1],[3,4],[6,7]]
[[1,2],[4,5],[7,8]]
[[0,1],[3,4],[6,7],[2,5]]
[[0,3],[1,4],[5,8]]
[[3,6],[4,7],[2,5]]
[[0,3],[1,4],[5,7],[2,6]]
[[1,3],[4,6]]
[[2,4],[5,6]]
[[2,3]]
--- 10
[[4,9],[3,8],[2,7],[1,6],[0,5]]
[[1,4],[6,9],[0,3],[5,8]]
[[0,2],[3,6],[7,9]]
[[0,1],[2,4],[5,7],[8,9]]
[[1,2],[4,6],[7,8],[3,5]]
[[2,5],[6,8],[1,3],[4,7]]
[[2,3],[6,7]]
[[3,4],[5,6]]
[[4,5]]
--- 11
[[0,1],[2,3],[4,5],[6,7],[8,9]]
[[1,3],[5,7],[0,2],[4,6],[8,10]]
[[1,2],[5,6],[9,10],[0,4],[3,7]]
[[1,5],[6,10],[4,8]]
[[5,9],[2,6],[0,4],[3,8]]
[[1,5],[6,10],[2,3],[8,9]]
[[1,4],[7,10],[3,5],[6,8]]
[[2,4],[7,9],[5,6]]
[[3,4],[7,8]]
--- 12
[[0,1],[2,3],[4,5],[6,7],[8,9],[10,11]]
[[1,3],[5,7],[9,11],[0,2],[4,6],[8,10]]
[[1,2],[5,6],[9,10],[0,4],[7,11]]
[[1,5],[6,10],[3,7],[4,8]]
[[5,9],[2,6],[0,4],[7,11],[3,8]]
[[1,5],[6,10],[2,3],[8,9]]
[[1,4],[7,10],[3,5],[6,8]]
[[2,4],[7,9],[5,6]]
[[3,4],[7,8]]
--- 13
[[1,7],[9,11],[3,4],[5,8],[0,12],[2,6]]
[[0,1],[2,3],[4,6],[8,11],[7,12],[5,9]]
[[0,2],[3,7],[10,11],[1,4],[6,12]]
[[7,8],[11,12],[4,9],[6,10]]
[[3,4],[5,6],[8,9],[10,11],[1,7]]
[[2,6],[9,11],[1,3],[4,7],[8,10],[0,5]]
[[2,5],[6,8],[9,10]]
[[1,2],[3,5],[7,8],[4,6]]
[[2,3],[4,5],[6,7],[8,9]]
[[3,4],[5,6]]
--- 14
[[0,1],[2,3],[4,5],[6,7],[8,9],[10,11],[12,13]]
[[0,2],[4,6],[8,10],[1,3],[5,7],[9,11]]
[[0,4],[8,12],[1,5],[9,13],[2,6],[3,7]]
[[0,8],[1,9],[2,10],[3,11],[4,12],[5,13]]
[[5,10],[6,9],[3,12],[7,11],[1,2],[4,8]]
[[1,4],[7,13],[2,8],[5,6],[9,10]]
[[2,4],[11,13],[3,8],[7,12]]
[[6,8],[10,12],[3,5],[7,9]]
[[3,4],[5,6],[7,8],[9,10],[11,12]]
[[6,7],[8,9]]
--- 15
[[0,1],[2,3],[4,5],[6,7],[8,9],[10,11],[12,13]]
[[0,2],[4,6],[8,10],[12,14],[1,3],[5,7],[9,11]]
[[0,4],[8,12],[1,5],[9,13],[2,6],[10,14],[3,7]]
[[0,8],[1,9],[2,10],[3,11],[4,12],[5,13],[6,14]]
[[5,10],[6,9],[3,12],[13,14],[7,11],[1,2],[4,8]]
[[1,4],[7,13],[2,8],[11,14],[5,6],[9,10]]
[[2,4],[11,13],[3,8],[7,12]]
[[6,8],[10,12],[3,5],[7,9]]
[[3,4],[5,6],[7,8],[9,10],[11,12]]
[[6,7],[8,9]]
--- 16
[[0,1],[2,3],[4,5],[6,7],[8,9],[10,11],[12,13],[14,15]]
[[0,2],[4,6],[8,10],[12,14],[1,3],[5,7],[9,11],[13,15]]
[[0,4],[8,12],[1,5],[9,13],[2,6],[10,14],[3,7],[11,15]]
[[0,8],[1,9],[2,10],[3,11],[4,12],[5,13],[6,14],[7,15]]
[[5,10],[6,9],[3,12],[13,14],[7,11],[1,2],[4,8]]
[[1,4],[7,13],[2,8],[11,14],[5,6],[9,10]]
[[2,4],[11,13],[3,8],[7,12]]
[[6,8],[10,12],[3,5],[7,9]]
[[3,4],[5,6],[7,8],[9,10],[11,12]]
[[6,7],[8,9]]
"""

In [9]:
print(code_networks(s))

template<typename T> void sort2(const T values[2],int order[2]){
ORDER_SWAP(0,1);
};

template<typename T> void sort3(const T values[3],int order[3]){
ORDER_SWAP(1,2);
ORDER_SWAP(0,2);
ORDER_SWAP(0,1);
};

template<typename T> void sort4(const T values[4],int order[4]){
ORDER_SWAP(0,1);ORDER_SWAP(2,3);
ORDER_SWAP(0,2);ORDER_SWAP(1,3);
ORDER_SWAP(1,2);
};

template<typename T> void sort5(const T values[5],int order[5]){
ORDER_SWAP(0,1);ORDER_SWAP(3,4);
ORDER_SWAP(2,4);
ORDER_SWAP(2,3);ORDER_SWAP(1,4);
ORDER_SWAP(0,3);
ORDER_SWAP(0,2);ORDER_SWAP(1,3);
ORDER_SWAP(1,2);
};

template<typename T> void sort6(const T values[6],int order[6]){
ORDER_SWAP(1,2);ORDER_SWAP(4,5);
ORDER_SWAP(0,2);ORDER_SWAP(3,5);
ORDER_SWAP(0,1);ORDER_SWAP(3,4);ORDER_SWAP(2,5);
ORDER_SWAP(0,3);ORDER_SWAP(1,4);
ORDER_SWAP(2,4);ORDER_SWAP(1,3);
ORDER_SWAP(2,3);
};

template<typename T> void sort7(const T values[7],int order[7]){
ORDER_SWAP(1,2);ORDER_SWAP(3,4);ORDER_SWAP(5,6);
ORDER_SWAP(0,2);ORDER_SWAP(3,5);ORDER_SWAP

In [3]:
import sys; sys.path.insert(0,"../..")
from agd.Metrics.hamiltonian import QuadraticHamiltonian



In [4]:
QuadraticHamiltonian

<function agd.Metrics.hamiltonian.QuadraticHamiltonian(HamiltonianBase)>

In [1]:
try: import cupy as cp
except ModuleNotFoundError: cp=None
    

import numpy as np
from agd import AutomaticDifferentiation as ad

In [2]:
x = ad.Sparse.identity(constant=np.array(1.))

In [3]:
x

spAD(array(1.), array([1.]), array([0]))

In [10]:

ad.cupy_support.ones_like(np.array(1.),shape=(1,1))

array([[1.]])

In [8]:
ad.cupy_generic.cp

In [9]:
def mycontainer():
    print("False"); yield False
    print("True"); yield True
    print("True, again"); yield True

In [11]:
list(mycontainer())

False
True
True, again


[False, True, True]

In [12]:
any(mycontainer())

False
True


True

In [4]:
a = np.array(1.)

In [7]:
a.astype(a.dtype) is a

False

In [6]:
a.dtype

dtype('float64')

In [9]:
np.arange((2,2))

TypeError: arange: scalar arguments expected instead of a tuple.

In [10]:
np.mgrid[0:5]

array([0, 1, 2, 3, 4])

In [11]:
np.mgrid[range(5)]

AttributeError: 'int' object has no attribute 'step'

In [12]:
range(5)

range(0, 5)

In [14]:
import inspect
inspect.getsource(np.mgrid)

TypeError: module, class, method, function, traceback, frame, or code object was expected, got MGridClass

In [15]:
help(np.mgrid)

Help on MGridClass in module numpy.lib.index_tricks object:

class MGridClass(nd_grid)
 |  `nd_grid` instance which returns a dense multi-dimensional "meshgrid".
 |  
 |  An instance of `numpy.lib.index_tricks.nd_grid` which returns an dense
 |  (or fleshed out) mesh-grid when indexed, so that each returned argument
 |  has the same shape.  The dimensions and number of the output arrays are
 |  equal to the number of indexing dimensions.  If the step length is not a
 |  complex number, then the stop is not inclusive.
 |  
 |  However, if the step length is a **complex number** (e.g. 5j), then
 |  the integer part of its magnitude is interpreted as specifying the
 |  number of points to create between the start and stop values, where
 |  the stop value **is inclusive**.
 |  
 |  Returns
 |  ----------
 |  mesh-grid `ndarrays` all of the same dimensions
 |  
 |  See Also
 |  --------
 |  numpy.lib.index_tricks.nd_grid : class of `ogrid` and `mgrid` objects
 |  ogrid : like mgrid but retu

In [23]:
np.mgrid.__getitem__((range(5),range(5))).dtype

dtype('int64')

In [27]:
np.mgrid[0:5:1]

array([0, 1, 2, 3, 4])

In [31]:
np.array(*np.broadcast(np.ix_(np.arange(2),np.arange(3)))

TypeError: data type not understood

In [37]:
np.array(np.meshgrid(np.linspace(0,1),np.linspace(0,2),copy=False )).shape

(2, 50, 50)