In [13]:
import sys; sys.path.insert(0,"../..") # Allow import of agd from parent directory 

from agd import HFMUtils
#from agd.HFMUtils import HFM_CUDA
import numpy as cp
import numpy as np
import time
from agd.AutomaticDifferentiation.Optimization import norm_infinity
from agd import AutomaticDifferentiation as ad
from agd import Metrics

def caster(arr): return cp.asarray(arr,dtype=np.float32) # array_float_caster
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%5.3g" % x))


n=4; ndim=4
hfmIn = HFMUtils.dictIn({
    'model':f'Riemann{ndim}',
    'verbosity':2,
    'seeds':[[0]*ndim],
#    'solver':'AGSI', 
#    'solver':'global_iteration',
    'raiseOnNonConvergence':False,
#    'nitermax_o':1,
#    'tol':5*1e-7,
#    'multiprecision':True,
#    'values_float64':True,
	'exportValues':True,
#	'factoringRadius':10,
#    'help':['nitermax_o','traits'],
	'dims':np.array([n]*ndim),
	'origin':[-0.5]*ndim,
	'gridScale':1.,
#	'order':2,
#	'order2_threshold':0.3,
#	'factoringRadius':10000,
#	'seedRadius':2,
#	'returns':'in_raw',

	'traits':{
	'debug_print':1,
	'shape_i':(2,)*ndim,'niter_i':10,
#	'niter_i':8,'shape_i':(4,)*ndim,
#	'niter_i':1,'shape_i':(8,8),
#	'niter_i':16,'shape_i':(8,8),
#	'niter_i':32,'shape_i':(16,16),
#	'niter_i':48,'shape_i':(24,24),
#	'niter_i':64,'shape_i':(32,32),
#   'debug_print':1,
#    'niter_i':1,
    'strict_iter_i_macro':1,
	'pruning_macro':0,
	'strict_iter_o_macro':1,
    },
#    'nonzero_untidy_kwargs':{'log2_size_i':8,'size2_i':256},
})

#hfmIn['metric'] = Metrics.Riemann(cp.eye(ndim,dtype=np.float32))
#hfmIn['metric'] = Metrics.Riemann.from_diagonal(cp.array((1,2,3,4,5),dtype=np.float32))
#x=np.array((1,2,3,4,5),dtype=np.float32)
#print(x.flags,"WRITEABLE")

#hfmIn['metric'] = Metrics.Riemann.needle(1+cp.arange(ndim,dtype=np.float32),caster(0.1),caster(1.))
hfmIn['metric'] = Metrics.Riemann.needle(cp.array((0.1,7.3,2.4,5.8,1.6)[:ndim],dtype=np.float32),caster(1.),caster(0.1))

print(hfmIn['metric'].m)

if False:
	hfmIn['model'] = f'Isotropic{ndim}'
	hfmIn.pop('metric')

#hfmOut = hfmIn.RunGPU()
#if n<=5: print(hfmOut['values'])

#exact = ad.Optimization.norm(hfmIn.Grid(),axis=0,ord=2)
#print("difference to exact",norm_infinity(exact-hfmOut['values']))


cpuIn = hfmIn.copy()
for key in ('traits','array_float_caster'): cpuIn.pop(key,None)
cpuIn['metric'] = np.array(cpuIn['metric'].to_HFM(),dtype=np.float64)
cpuOut = cpuIn.Run()

#diff = cpuOut['values']-hfmOut['values'].get()
#print("LInf error: ",np.max(np.abs(diff)))
#if n<=20: print(diff)

cpuOut.keys()

[[0.0101 0.0078 0.00256 0.00619]
 [0.0078 0.579 0.187 0.452]
 [0.00256 0.187 0.0715 0.149]
 [0.00619 0.452 0.149 0.369]]
Returned with exit code  -11


dict_keys(['FMCPUTime', 'GeodesicCPUTime', 'MaxStencilWidth', 'StencilCPUTime', 'defaulted', 'nAccepted', 'unusedFromCompute', 'unusedFromUser', 'unusedHelp', 'values', 'visitedUnset', 'retcode'])

In [6]:
cpuOut['values']

array([[[[    0,  1.49,  2.49,  3.34],
         [0.638,  1.87,  2.76,  3.59],
         [ 1.23,  2.23,  3.08,  3.89],
         [  1.8,  2.58,  3.41,  4.19]],

        [[ 1.73,  2.63,  3.46,  4.28],
         [ 2.07,  2.91,  3.71,  4.52],
         [ 2.42,  3.23,  4.02,  4.83],
         [ 2.77,  3.55,  4.32,  5.14]],

        [[ 2.87,  3.63,  4.41,  5.22],
         [ 3.12,  3.88,  4.65,  5.47],
         [ 3.43,  4.19,  4.96,   5.8],
         [ 3.75,  4.49,  5.28,  6.15]],

        [[ 3.86,  4.58,  5.36,  6.25],
         [  4.1,  4.83,  5.63,  6.56],
         [ 4.39,  5.15,  5.98,  7.11],
         [ 4.69,  5.47,  6.33,  7.68]]],


       [[[0.103,  1.52,  2.51,  3.36],
         [0.684,   1.9,  2.77,   3.6],
         [ 1.26,  2.25,   3.1,   3.9],
         [ 1.82,   2.6,  3.42,  4.21]],

        [[ 1.75,  2.65,  3.48,  4.29],
         [ 2.09,  2.93,  3.73,  4.53],
         [ 2.44,  3.25,  4.03,  4.84],
         [ 2.79,  3.57,  4.34,  5.15]],

        [[ 2.88,  3.64,  4.42,  5.24],
         [ 