In [1]:
import sys; sys.path.insert(0,"../..")
from agd import AutomaticDifferentiation as ad
import numpy as np
from collections import OrderedDict,namedtuple
from types import SimpleNamespace
import inspect

In [2]:
arr = ad.Dense.identity(constant=(3,1,2))

In [3]:
arr2=arr.copy()
np.copyto._implementation(arr2,0,casting='unsafe')

In [4]:
np.ones_like(arr)

denseAD(array([1, 1, 1]),array([], shape=(3, 0), dtype=int64))

In [5]:
np.full_like(arr,2.)

denseAD(array([2, 2, 2]),array([], shape=(3, 0), dtype=int64))

In [6]:
arr2

denseAD(array([0, 0, 0]),
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]]))

In [9]:
np.maximum(np.array((1,3,2)),arr)

denseAD(array([3, 3, 2]),
array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 1]]))

In [8]:
np.ones_like._implementation(arr,shape=(3,3))

denseAD(array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]]),array([], shape=(3, 3, 0), dtype=int64))

In [11]:
np.stack((np.array((1,3,2)),arr),axis=0)

denseAD(array([[1, 3, 2],
       [3, 1, 2]]),
array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]]))

In [7]:
np.sum._implementation(arr,axis=0)

denseAD(array(6),array([1, 1, 1]))

In [6]:
np.moveaxis._implementation(arr,0,-1)

denseAD(array([3, 1, 2]),
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]]))

In [18]:
np.sum.__dict__

{'__wrapped__': <function numpy.core.fromnumeric.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>,
 '_implementation': <function numpy.core.fromnumeric.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>}

In [16]:
np.moveaxis._implementation(arr,0,0)

hi


denseAD(array([3, 1, 2]),
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]]))

In [8]:
print(inspect.getsource(np.ones_like))

@array_function_dispatch(_ones_like_dispatcher)
def ones_like(a, dtype=None, order='K', subok=True, shape=None):
    """
    Return an array of ones with the same shape and type as a given array.

    Parameters
    ----------
    a : array_like
        The shape and data-type of `a` define these same attributes of
        the returned array.
    dtype : data-type, optional
        Overrides the data type of the result.

        .. versionadded:: 1.6.0
    order : {'C', 'F', 'A', or 'K'}, optional
        Overrides the memory layout of the result. 'C' means C-order,
        'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous,
        'C' otherwise. 'K' means match the layout of `a` as closely
        as possible.

        .. versionadded:: 1.6.0
    subok : bool, optional.
        If True, then the newly created array will use the sub-class
        type of 'a', otherwise it will be a base-class array. Defaults
        to True.
    shape : int or sequence of ints, optional.
  

In [11]:
np.moveaxis.__dict__

{'__wrapped__': <function numpy.core.numeric.moveaxis(a, source, destination)>,
 '_implementation': <function numpy.core.numeric.moveaxis(a, source, destination)>}

In [8]:
np.moveaxis(super(type(arr),arr),0,-1)

AttributeError: 'denseAD' object has no attribute 'coef'

In [3]:
np.full_like(arr,shape=(3,3),fill_value=0.)

__array_function__ <function full_like at 0x115376af0>


denseAD(array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]]),array([], shape=(3, 3, 0), dtype=int64))

In [4]:
np.ones_like(arr,shape=(3,3))

__array_function__ <function ones_like at 0x1153768b0>


denseAD(array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]]),array([], shape=(3, 3, 0), dtype=int64))

In [5]:
np.broadcast_to(arr,shape=(3,3))

__array_function__ <function broadcast_to at 0x115525b80>


denseAD(array([[3, 1, 2],
       [3, 1, 2],
       [3, 1, 2]]),
array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]]))

In [6]:
np.where(arr>=2,arr,0.)

__array_function__ <function where at 0x11008a160>


denseAD(array([3, 0, 2]),
array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 1]]))

In [7]:
np.sort(arr)

__array_function__ <function sort at 0x115395c10>
__array_function__ <function take_along_axis at 0x1155470d0>


denseAD(array([1, 2, 3]),
array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0]]))

In [8]:
arr.flat[2]

2

In [9]:
scarr = ad.Dense.identity(constant=1.)

In [10]:
np.float64(0.) + scarr

1.0

In [12]:
np.float64(1.).__array_priority__

-1000000.0

In [13]:
np.array(1.).__array_priority__

0.0

In [15]:
type(np.float64(1.)+np.array(1.))

numpy.float64