In [1]:
try: import cupy as cp
except ModuleNotFoundError: cp=None
    
import sys; sys.path.insert(0,"../..")
import numpy as np
from agd import AutomaticDifferentiation as ad

In [2]:
x = ad.Sparse.identity(constant=np.array(1.))

In [3]:
x

spAD(array(1.), array([1.]), array([0]))

In [10]:

ad.cupy_support.ones_like(np.array(1.),shape=(1,1))

array([[1.]])

In [8]:
ad.cupy_generic.cp

In [9]:
def mycontainer():
    print("False"); yield False
    print("True"); yield True
    print("True, again"); yield True

In [11]:
list(mycontainer())

False
True
True, again


[False, True, True]

In [12]:
any(mycontainer())

False
True


True

In [4]:
a = np.array(1.)

In [7]:
a.astype(a.dtype) is a

False

In [6]:
a.dtype

dtype('float64')

In [9]:
np.arange((2,2))

TypeError: arange: scalar arguments expected instead of a tuple.

In [10]:
np.mgrid[0:5]

array([0, 1, 2, 3, 4])

In [11]:
np.mgrid[range(5)]

AttributeError: 'int' object has no attribute 'step'

In [12]:
range(5)

range(0, 5)

In [14]:
import inspect
inspect.getsource(np.mgrid)

TypeError: module, class, method, function, traceback, frame, or code object was expected, got MGridClass

In [15]:
help(np.mgrid)

Help on MGridClass in module numpy.lib.index_tricks object:

class MGridClass(nd_grid)
 |  `nd_grid` instance which returns a dense multi-dimensional "meshgrid".
 |  
 |  An instance of `numpy.lib.index_tricks.nd_grid` which returns an dense
 |  (or fleshed out) mesh-grid when indexed, so that each returned argument
 |  has the same shape.  The dimensions and number of the output arrays are
 |  equal to the number of indexing dimensions.  If the step length is not a
 |  complex number, then the stop is not inclusive.
 |  
 |  However, if the step length is a **complex number** (e.g. 5j), then
 |  the integer part of its magnitude is interpreted as specifying the
 |  number of points to create between the start and stop values, where
 |  the stop value **is inclusive**.
 |  
 |  Returns
 |  ----------
 |  mesh-grid `ndarrays` all of the same dimensions
 |  
 |  See Also
 |  --------
 |  numpy.lib.index_tricks.nd_grid : class of `ogrid` and `mgrid` objects
 |  ogrid : like mgrid but retu

In [23]:
np.mgrid.__getitem__((range(5),range(5))).dtype

dtype('int64')

In [27]:
np.mgrid[0:5:1]

array([0, 1, 2, 3, 4])

In [31]:
np.array(*np.broadcast(np.ix_(np.arange(2),np.arange(3)))

TypeError: data type not understood

In [37]:
np.array(np.meshgrid(np.linspace(0,1),np.linspace(0,2),copy=False )).shape

(2, 50, 50)