In [1]:
import sys; sys.path.insert(0,"../..")
from agd import AutomaticDifferentiation as ad
import numpy as np
from collections import OrderedDict,namedtuple
from types import SimpleNamespace
import inspect

In [2]:
arr = ad.Dense.identity(constant=(3,1,2))

In [7]:
np.sum._implementation(arr,axis=0)

denseAD(array(6),array([1, 1, 1]))

In [6]:
np.moveaxis._implementation(arr,0,-1)

denseAD(array([3, 1, 2]),
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]]))

In [18]:
np.sum.__dict__

{'__wrapped__': <function numpy.core.fromnumeric.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>,
 '_implementation': <function numpy.core.fromnumeric.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>}

In [16]:
np.moveaxis._implementation(arr,0,0)

hi


denseAD(array([3, 1, 2]),
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]]))

In [14]:
print(inspect.getsource(np.moveaxis))

@array_function_dispatch(_moveaxis_dispatcher)
def moveaxis(a, source, destination):
    """
    Move axes of an array to new positions.

    Other axes remain in their original order.

    .. versionadded:: 1.11.0

    Parameters
    ----------
    a : np.ndarray
        The array whose axes should be reordered.
    source : int or sequence of int
        Original positions of the axes to move. These must be unique.
    destination : int or sequence of int
        Destination positions for each of the original axes. These must also be
        unique.

    Returns
    -------
    result : np.ndarray
        Array with moved axes. This array is a view of the input array.

    See Also
    --------
    transpose: Permute the dimensions of an array.
    swapaxes: Interchange two axes of an array.

    Examples
    --------

    >>> x = np.zeros((3, 4, 5))
    >>> np.moveaxis(x, 0, -1).shape
    (4, 5, 3)
    >>> np.moveaxis(x, -1, 0).shape
    (5, 3, 4)

    These all achieve the same res

In [11]:
np.moveaxis.__dict__

{'__wrapped__': <function numpy.core.numeric.moveaxis(a, source, destination)>,
 '_implementation': <function numpy.core.numeric.moveaxis(a, source, destination)>}

In [8]:
np.moveaxis(super(type(arr),arr),0,-1)

AttributeError: 'denseAD' object has no attribute 'coef'

In [3]:
np.full_like(arr,shape=(3,3),fill_value=0.)

__array_function__ <function full_like at 0x115376af0>


denseAD(array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]]),array([], shape=(3, 3, 0), dtype=int64))

In [4]:
np.ones_like(arr,shape=(3,3))

__array_function__ <function ones_like at 0x1153768b0>


denseAD(array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]]),array([], shape=(3, 3, 0), dtype=int64))

In [5]:
np.broadcast_to(arr,shape=(3,3))

__array_function__ <function broadcast_to at 0x115525b80>


denseAD(array([[3, 1, 2],
       [3, 1, 2],
       [3, 1, 2]]),
array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]]))

In [6]:
np.where(arr>=2,arr,0.)

__array_function__ <function where at 0x11008a160>


denseAD(array([3, 0, 2]),
array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 1]]))

In [7]:
np.sort(arr)

__array_function__ <function sort at 0x115395c10>
__array_function__ <function take_along_axis at 0x1155470d0>


denseAD(array([1, 2, 3]),
array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0]]))

In [8]:
arr.flat[2]

2

In [9]:
scarr = ad.Dense.identity(constant=1.)

In [10]:
np.float64(0.) + scarr

1.0

In [12]:
np.float64(1.).__array_priority__

-1000000.0

In [13]:
np.array(1.).__array_priority__

0.0

In [15]:
type(np.float64(1.)+np.array(1.))

numpy.float64