In [12]:
import sys; sys.path.insert(0,"../..")
from agd import AutomaticDifferentiation as ad
import numpy as np
from collections import OrderedDict,namedtuple
from types import SimpleNamespace
import inspect
import numbers

In [1]:
len([1,1,0,1,0,0,1,0,0,0,0,1,1,0,1,0,0,1,0,0,0,0,0,1,1,1,0,0,1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,0,-1,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0])

100

In [2]:
len([1,1,0,1,0,0,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,0
		,0,1,1,1,1,0,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0,-1,0,0,-1,0,0,0,0,
		-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,-1,0,0,0,0,0,0
		,0,0,0,0,0,-1,0,-1,0,0,0,0,0,0,0,1,0,0,0])

100

In [31]:
s4="""[[0,1],[2,3]]
[[0,2],[1,3]]
[[1,2]]
"""

In [62]:
def code_line(s):
    s=s.replace("[[","ORDER_SWAP(")
    s=s.replace("],[",");ORDER_SWAP(")
    s=s.replace("]]",");")
    return s

def code_network(s):
    s = s.split("\n")
    n = int(s[0])
    s = (f"template<> void network_sort<{n}> (const Scalar values[{n}],Int order[{n}])"+"{\n"+
         "\n".join(code_line(l) for l in s[1:])+"}\n")
    return s
def code_networks(s):
    s = s.split('--- ')[1:]
    return "\n".join(code_network(l) for l in s)

In [64]:
s = """
--- 2
[[0,1]]
--- 3
[[1,2]]
[[0,2]]
[[0,1]]
--- 4
[[0,1],[2,3]]
[[0,2],[1,3]]
[[1,2]]
--- 5
[[0,1],[3,4]]
[[2,4]]
[[2,3],[1,4]]
[[0,3]]
[[0,2],[1,3]]
[[1,2]]
--- 6
[[1,2],[4,5]]
[[0,2],[3,5]]
[[0,1],[3,4],[2,5]]
[[0,3],[1,4]]
[[2,4],[1,3]]
[[2,3]]
--- 7
[[1,2],[3,4],[5,6]]
[[0,2],[3,5],[4,6]]
[[0,1],[4,5],[2,6]]
[[0,4],[1,5]]
[[0,3],[2,5]]
[[1,3],[2,4]]
[[2,3]]
--- 8
[[0,1],[2,3],[4,5],[6,7]]
[[0,2],[1,3],[4,6],[5,7]]
[[1,2],[5,6],[0,4],[3,7]]
[[1,5],[2,6]]
[[1,4],[3,6]]
[[2,4],[3,5]]
[[3,4]]
--- 9
[[0,1],[3,4],[6,7]]
[[1,2],[4,5],[7,8]]
[[0,1],[3,4],[6,7],[2,5]]
[[0,3],[1,4],[5,8]]
[[3,6],[4,7],[2,5]]
[[0,3],[1,4],[5,7],[2,6]]
[[1,3],[4,6]]
[[2,4],[5,6]]
[[2,3]]
--- 10
[[4,9],[3,8],[2,7],[1,6],[0,5]]
[[1,4],[6,9],[0,3],[5,8]]
[[0,2],[3,6],[7,9]]
[[0,1],[2,4],[5,7],[8,9]]
[[1,2],[4,6],[7,8],[3,5]]
[[2,5],[6,8],[1,3],[4,7]]
[[2,3],[6,7]]
[[3,4],[5,6]]
[[4,5]]
--- 11
[[0,1],[2,3],[4,5],[6,7],[8,9]]
[[1,3],[5,7],[0,2],[4,6],[8,10]]
[[1,2],[5,6],[9,10],[0,4],[3,7]]
[[1,5],[6,10],[4,8]]
[[5,9],[2,6],[0,4],[3,8]]
[[1,5],[6,10],[2,3],[8,9]]
[[1,4],[7,10],[3,5],[6,8]]
[[2,4],[7,9],[5,6]]
[[3,4],[7,8]]
--- 12
[[0,1],[2,3],[4,5],[6,7],[8,9],[10,11]]
[[1,3],[5,7],[9,11],[0,2],[4,6],[8,10]]
[[1,2],[5,6],[9,10],[0,4],[7,11]]
[[1,5],[6,10],[3,7],[4,8]]
[[5,9],[2,6],[0,4],[7,11],[3,8]]
[[1,5],[6,10],[2,3],[8,9]]
[[1,4],[7,10],[3,5],[6,8]]
[[2,4],[7,9],[5,6]]
[[3,4],[7,8]]
--- 13
[[1,7],[9,11],[3,4],[5,8],[0,12],[2,6]]
[[0,1],[2,3],[4,6],[8,11],[7,12],[5,9]]
[[0,2],[3,7],[10,11],[1,4],[6,12]]
[[7,8],[11,12],[4,9],[6,10]]
[[3,4],[5,6],[8,9],[10,11],[1,7]]
[[2,6],[9,11],[1,3],[4,7],[8,10],[0,5]]
[[2,5],[6,8],[9,10]]
[[1,2],[3,5],[7,8],[4,6]]
[[2,3],[4,5],[6,7],[8,9]]
[[3,4],[5,6]]
--- 14
[[0,1],[2,3],[4,5],[6,7],[8,9],[10,11],[12,13]]
[[0,2],[4,6],[8,10],[1,3],[5,7],[9,11]]
[[0,4],[8,12],[1,5],[9,13],[2,6],[3,7]]
[[0,8],[1,9],[2,10],[3,11],[4,12],[5,13]]
[[5,10],[6,9],[3,12],[7,11],[1,2],[4,8]]
[[1,4],[7,13],[2,8],[5,6],[9,10]]
[[2,4],[11,13],[3,8],[7,12]]
[[6,8],[10,12],[3,5],[7,9]]
[[3,4],[5,6],[7,8],[9,10],[11,12]]
[[6,7],[8,9]]
--- 15
[[0,1],[2,3],[4,5],[6,7],[8,9],[10,11],[12,13]]
[[0,2],[4,6],[8,10],[12,14],[1,3],[5,7],[9,11]]
[[0,4],[8,12],[1,5],[9,13],[2,6],[10,14],[3,7]]
[[0,8],[1,9],[2,10],[3,11],[4,12],[5,13],[6,14]]
[[5,10],[6,9],[3,12],[13,14],[7,11],[1,2],[4,8]]
[[1,4],[7,13],[2,8],[11,14],[5,6],[9,10]]
[[2,4],[11,13],[3,8],[7,12]]
[[6,8],[10,12],[3,5],[7,9]]
[[3,4],[5,6],[7,8],[9,10],[11,12]]
[[6,7],[8,9]]
--- 16
[[0,1],[2,3],[4,5],[6,7],[8,9],[10,11],[12,13],[14,15]]
[[0,2],[4,6],[8,10],[12,14],[1,3],[5,7],[9,11],[13,15]]
[[0,4],[8,12],[1,5],[9,13],[2,6],[10,14],[3,7],[11,15]]
[[0,8],[1,9],[2,10],[3,11],[4,12],[5,13],[6,14],[7,15]]
[[5,10],[6,9],[3,12],[13,14],[7,11],[1,2],[4,8]]
[[1,4],[7,13],[2,8],[11,14],[5,6],[9,10]]
[[2,4],[11,13],[3,8],[7,12]]
[[6,8],[10,12],[3,5],[7,9]]
[[3,4],[5,6],[7,8],[9,10],[11,12]]
[[6,7],[8,9]]"""
#s = s.split('--- ')
print(code_networks(s))

template<> void network_sort<2> (const Scalar values[2],Int order[2]){
ORDER_SWAP(0,1);
}

template<> void network_sort<3> (const Scalar values[3],Int order[3]){
ORDER_SWAP(1,2);
ORDER_SWAP(0,2);
ORDER_SWAP(0,1);
}

template<> void network_sort<4> (const Scalar values[4],Int order[4]){
ORDER_SWAP(0,1);ORDER_SWAP(2,3);
ORDER_SWAP(0,2);ORDER_SWAP(1,3);
ORDER_SWAP(1,2);
}

template<> void network_sort<5> (const Scalar values[5],Int order[5]){
ORDER_SWAP(0,1);ORDER_SWAP(3,4);
ORDER_SWAP(2,4);
ORDER_SWAP(2,3);ORDER_SWAP(1,4);
ORDER_SWAP(0,3);
ORDER_SWAP(0,2);ORDER_SWAP(1,3);
ORDER_SWAP(1,2);
}

template<> void network_sort<6> (const Scalar values[6],Int order[6]){
ORDER_SWAP(1,2);ORDER_SWAP(4,5);
ORDER_SWAP(0,2);ORDER_SWAP(3,5);
ORDER_SWAP(0,1);ORDER_SWAP(3,4);ORDER_SWAP(2,5);
ORDER_SWAP(0,3);ORDER_SWAP(1,4);
ORDER_SWAP(2,4);ORDER_SWAP(1,3);
ORDER_SWAP(2,3);
}

template<> void network_sort<7> (const Scalar values[7],Int order[7]){
ORDER_SWAP(1,2);ORDER_SWAP(3,4);ORDER_SWAP(5,6);
ORDER_SWAP(

In [46]:
np.set_printoptions(edgeitems=30, linewidth=100000, 
    formatter=dict(float=lambda x: "%5.9g" % x))

In [25]:
def cos_sin_table(n):
    angles = (np.arange(n)+0.5)*np.pi/n
    return np.cos(angles),np.sin(angles)

In [26]:
cos_sin_table(5)

(array([0.951056516, 0.587785252, 6.123234e-17, -0.587785252, -0.951056516]),
 array([0.309016994, 0.809016994,     1, 0.809016994, 0.309016994]))

In [27]:
cos_sin_table(9)

(array([0.984807753, 0.866025404, 0.64278761, 0.342020143, 6.123234e-17, -0.342020143, -0.64278761, -0.866025404, -0.984807753]),
 array([0.173648178,   0.5, 0.766044443, 0.939692621,     1, 0.939692621, 0.766044443,   0.5, 0.173648178]))

In [2]:
arr = ad.Dense.identity(constant=(3,1,2))

In [13]:
isinstance(2,numbers.Integral)

True

In [3]:
arr2=arr.copy()
np.copyto._implementation(arr2,0,casting='unsafe')

In [4]:
np.ones_like(arr)

denseAD(array([1, 1, 1]),array([], shape=(3, 0), dtype=int64))

In [5]:
np.full_like(arr,2.)

denseAD(array([2, 2, 2]),array([], shape=(3, 0), dtype=int64))

In [6]:
arr2

denseAD(array([0, 0, 0]),
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]]))

In [9]:
np.maximum(np.array((1,3,2)),arr)

denseAD(array([3, 3, 2]),
array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 1]]))

In [8]:
np.ones_like._implementation(arr,shape=(3,3))

denseAD(array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]]),array([], shape=(3, 3, 0), dtype=int64))

In [11]:
np.stack((np.array((1,3,2)),arr),axis=0)

denseAD(array([[1, 3, 2],
       [3, 1, 2]]),
array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]]))

In [7]:
np.sum._implementation(arr,axis=0)

denseAD(array(6),array([1, 1, 1]))

In [6]:
np.moveaxis._implementation(arr,0,-1)

denseAD(array([3, 1, 2]),
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]]))

In [18]:
np.sum.__dict__

{'__wrapped__': <function numpy.core.fromnumeric.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>,
 '_implementation': <function numpy.core.fromnumeric.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>}

In [16]:
np.moveaxis._implementation(arr,0,0)

hi


denseAD(array([3, 1, 2]),
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]]))

In [8]:
print(inspect.getsource(np.ones_like))

@array_function_dispatch(_ones_like_dispatcher)
def ones_like(a, dtype=None, order='K', subok=True, shape=None):
    """
    Return an array of ones with the same shape and type as a given array.

    Parameters
    ----------
    a : array_like
        The shape and data-type of `a` define these same attributes of
        the returned array.
    dtype : data-type, optional
        Overrides the data type of the result.

        .. versionadded:: 1.6.0
    order : {'C', 'F', 'A', or 'K'}, optional
        Overrides the memory layout of the result. 'C' means C-order,
        'F' means F-order, 'A' means 'F' if `a` is Fortran contiguous,
        'C' otherwise. 'K' means match the layout of `a` as closely
        as possible.

        .. versionadded:: 1.6.0
    subok : bool, optional.
        If True, then the newly created array will use the sub-class
        type of 'a', otherwise it will be a base-class array. Defaults
        to True.
    shape : int or sequence of ints, optional.
  

In [11]:
np.moveaxis.__dict__

{'__wrapped__': <function numpy.core.numeric.moveaxis(a, source, destination)>,
 '_implementation': <function numpy.core.numeric.moveaxis(a, source, destination)>}

In [8]:
np.moveaxis(super(type(arr),arr),0,-1)

AttributeError: 'denseAD' object has no attribute 'coef'

In [3]:
np.full_like(arr,shape=(3,3),fill_value=0.)

__array_function__ <function full_like at 0x115376af0>


denseAD(array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]]),array([], shape=(3, 3, 0), dtype=int64))

In [4]:
np.ones_like(arr,shape=(3,3))

__array_function__ <function ones_like at 0x1153768b0>


denseAD(array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]]),array([], shape=(3, 3, 0), dtype=int64))

In [5]:
np.broadcast_to(arr,shape=(3,3))

__array_function__ <function broadcast_to at 0x115525b80>


denseAD(array([[3, 1, 2],
       [3, 1, 2],
       [3, 1, 2]]),
array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]]))

In [6]:
np.where(arr>=2,arr,0.)

__array_function__ <function where at 0x11008a160>


denseAD(array([3, 0, 2]),
array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 1]]))

In [7]:
np.sort(arr)

__array_function__ <function sort at 0x115395c10>
__array_function__ <function take_along_axis at 0x1155470d0>


denseAD(array([1, 2, 3]),
array([[0, 1, 0],
       [0, 0, 1],
       [1, 0, 0]]))

In [8]:
arr.flat[2]

2

In [9]:
scarr = ad.Dense.identity(constant=1.)

In [10]:
np.float64(0.) + scarr

1.0

In [12]:
np.float64(1.).__array_priority__

-1000000.0

In [13]:
np.array(1.).__array_priority__

0.0

In [15]:
type(np.float64(1.)+np.array(1.))

numpy.float64